let

CalendarioM = let
 
StartDate = #date(2020,1,1),

EndDate = #date(2025,12,31),

DateTable = List.Dates(StartDate, Duration.Days(EndDate-StartDate), #duration(1, 0, 0, 0)),

YearColumn = List.Transform(DateTable, each Date.Year(_)),

YearNameColumn = List.Transform(DateTable, each "" & Text.End(Text.From(Date.Year(_)),2)),

QuarterColumn = List.Transform(DateTable, each Date.QuarterOfYear(_)),

QuarterNameColumn = List.Transform(DateTable, each "T" & Text.From (Date.QuarterOfYear(_))),

MonthColumn = List.Transform(DateTable, each Date.Month(_)),

MonthNameColumn = List.Transform(DateTable, each Text.Start(Date.MonthName(_),3)),

WeekColumn = List.Transform(DateTable, each Date.WeekOfYear(_)),

WeekNameColumn = List.Transform(WeekColumn, each "CW" & Text.From(Number.Round(_, 0))),

DayColumn = List.Transform(DateTable, each Date.Day(_))
 
//Nome das colunas
 
in

Table.FromColumns({

DateTable,

YearColumn,

YearNameColumn,

QuarterColumn,

QuarterNameColumn,

MonthColumn,

MonthNameColumn,

WeekColumn,

WeekNameColumn,

DayColumn

}, {"Data", "Ano", "Nome do Ano", "Trimestre", "Nome do Trimestre", "Mês", "Nome do Mês", "Semana", "Nome da Semana", "Dia"}),
 
//Formatação
 
    #"Tipo Alterado" = Table.TransformColumnTypes(CalendarioM,{{"Data", type date}}),

    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"Nome do Mês", Text.Proper, type text}}),

    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colocar Cada Palavra Em Maiúscula",{{"Ano", Int64.Type}, {"Trimestre", Int64.Type}, {"Mês", Int64.Type}, {"Semana", Int64.Type}, {"Dia", Int64.Type}, {"Nome da Semana", type text}, {"Nome do Trimestre", type text}}),

    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado1",{{"Data", Order.Ascending}}),
 
//Índice Adicionado
 
    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas Classificadas", "Índice", 1, 1, Int64.Type),

    #"Colunas Reordenadas" = Table.ReorderColumns(#"Índice Adicionado",{"Índice", "Data", "Ano", "Nome do Ano", "Trimestre", "Nome do Trimestre", "Mês", "Nome do Mês", "Semana", "Nome da Semana", "Dia"}),

    #"Linhas Classificadas1" = Table.Sort(#"Colunas Reordenadas",{{"Índice", Order.Ascending}}),
 
//Coluna de ordem do mês
 
    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Linhas Classificadas1", "Mês (Ordem)", each Text.PadStart(Text.From([Mês], "pt-BR"), 2, "0"), type text),
 
//Coluna de Ano/Mês
 
    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Coluna Personalizada Adicionada", "Ano/Mês", each Text.Combine({Text.From([Ano], "pt-BR"), [#"Mês (Ordem)"]}, ""), type text),

    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida",{{"Ano/Mês", type number}}),

    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Tipo Alterado2", "Nome Ano/Mês", each Text.Combine({[Nome do Ano], [Nome do Mês]}, "/"), type text),
 
//Apagar coluna de ordem do mês
 
    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Mesclada Inserida1",{"Mês (Ordem)"}),

    #"Coluna Mesclada Inserida2" = Table.AddColumn(#"Colunas Removidas", "Ano/Semana", each Text.Combine({Text.From([Ano], "pt-BR"), Text.From([Semana], "pt-BR")}, ""), type text),

    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida2",{{"Ano/Semana", type number}}),

    #"Coluna Mesclada Inserida3" = Table.AddColumn(#"Tipo Alterado3", "Nome Ano/Semana", each Text.Combine({[Nome do Ano], [Nome da Semana]}, "/"), type text)

in

    #"Coluna Mesclada Inserida3"
