let
  Source = List.Numbers(0, 50000, 0.01), 
  #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), {"Decimal"}), 
  #"Tipo Alterado" = Table.TransformColumnTypes(#"Converted to Table",{{"Decimal", type number}}),
    Arredondado = Table.TransformColumns(#"Tipo Alterado",{{"Decimal", each Number.Round(_, 2), type number}}),
    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(Arredondado, "Horas", each if Text.EndsWith(Text.From([Decimal]), "99") then
Number.FromText(Text.BeforeDelimiter(Text.From([Decimal]), ",")) + 1 else Text.BeforeDelimiter(Text.From([Decimal]), ",")),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Texto Inserido Antes do Delimitador",{{"Horas", type number}}),
    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Tipo Alterado1", "Minutos", each if (([Decimal] - [Horas]) * 60) < 0 then 0 else ([Decimal] - [Horas]) * 60),
    Arredondado1 = Table.TransformColumns(#"Texto Inserido Após o Delimitador",{{"Minutos", each Number.Round(_, 0), type number}}),
    #"Personalização Adicionada" = Table.AddColumn(Arredondado1, "Duração amigável", each
if [Horas] = 0 then Text.From([Minutos]) & "min" else
if [Minutos] = 0 then Text.From([Horas]) & "h" else
Text.From([Horas]) & "h" & Text.From([Minutos]) & "min"),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Duração amigável", type text}})
in
    #"Tipo Alterado2"
