let
    Source = List.Times(#time(0,0,0),24*60,#duration(0,0,1,0)),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Time"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Time", type time}}),
    #"Removed Seconds" = Table.TransformColumns(#"Changed Type", {{"Time", each Time.FromText(Time.ToText(_, "hh:mm"))}}),
    #"Inserted Hour" = Table.AddColumn(#"Removed Seconds", "Hour", each Time.Hour([Time]), Int64.Type),
    #"Inserted Minute" = Table.AddColumn(#"Inserted Hour", "Minute", each Time.Minute([Time]), Int64.Type),
    #"Added Conditional Column" = Table.AddColumn(#"Inserted Minute", "AM/PM", each if [Hour] < 12 then "a.m." else "p.m."),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"AM/PM", type text}})
in
    #"Changed Type1"
